name: instagram_clone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  #  GetX is an extra-light and powerful solution for Flutter. It combines high-performance state management,
  #  intelligent dependency injection, and route management quickly and practically.
  get: ^4.6.5
  #  A fast, extra light and synchronous key-value in memory, which backs up data to disk at each operation.
  #  It is written entirely in Dart and easily integrates with Get framework of Flutter.
  get_storage: ^2.0.3
  #  Draw SVG (and some Android VectorDrawable (XML)) files on a Flutter Widget.
  flutter_svg: ^1.1.5
  #A library for Dart that generates fake data.
  faker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/bottom_navbar/
    - assets/icons/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
