name: instagram_clone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #  GetX is an extra-light and powerful solution for Flutter. It combines high-performance state management,
  #  intelligent dependency injection, and route management quickly and practically.
  get: ^4.6.5
  #  A fast, extra light and synchronous key-value in memory, which backs up data to disk at each operation.
  #  It is written entirely in Dart and easily integrates with Get framework of Flutter.
  get_storage: ^2.0.3
  #  Draw SVG (and some Android VectorDrawable (XML)) files on a Flutter Widget.
  flutter_svg: ^1.1.5
  # A library for Dart that generates fake data.
  faker: ^2.0.0
  # A flutter library to show images from the internet and keep them in the cache directory.
  cached_network_image: ^3.2.2
  # A Flutter plugin for iOS, Android and Web for playing back video on a Widget surface.
  video_player: ^2.4.7
  # A Flutter package to extract prominent colors from an Image, typically used to find colors for a user interface.
  palette_generator: ^0.3.3+2
  # Provides a collection of Flutter grids layouts.
  flutter_staggered_grid_view: ^0.4.0
  # This Flutter package includes the widget ExpandableText which you can use to initially only show a defined number of lines of a probably long text.
  expandable_text: ^2.3.0
  # A Flutter widget that scrolls text infinitely. Provides many customizations including custom scroll directions, durations, curves as well as pauses after every round.
  marquee: ^2.2.3
  # A flutter plugin to get all images, audios, videos and files location path in json format.
  flutter_storage_path: ^1.0.4
  # A Flutter plugin for iOS, Android and Web allowing access to the device cameras.
  camera: ^0.10.0+4




  #Provides internationalization and localization facilities, including message translation, plurals and genders,
  #date/number formatting and parsing, and bidirectional text.
  intl: ^0.17.0
  #A flutter list that allows scrolling to a specific item in the list.
  #Also allows determining what items are currently visible.
  #scrollable_positioned_list: ^0.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/bottom_navbar/
    - assets/high_light_images/
    - assets/icons/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
